#!/usr/bin/env python3
"""
Regime-coverage map (Bot Fleet — backlog RESEARCH item 1).

THE QUESTION: across the C1 956-day labeled history, how many days a year do our
locked gates fire NOTHING, and what do those uncovered days look like? Every new
research dollar should aim at the biggest empty cell.

INPUT: data/c1_rows.csv  (written by lean/c1_regime.py -> QC ObjectStore -> exported
       by Andy). Schema: date,atm_iv,atr5,gap_pct,exc,held,stayed075,pnl,win
         held      = 1 short strikes survived (CHOP / IC day) | 0 touched (ran = trend)
         stayed075 = 1 full-day excursion <= 0.75% (pure-range cross-check)
         exc       = full-day % excursion from prior close
         atm_iv    = morning implied-vol regime feature (RELATIVE signal; noisy level)

COVERAGE MODEL (atm_iv is the only in-dataset regime axis):
  - IC-covered      = calm cohort: atm_iv in the low band AND HELD-rate high (the IC has
                      edge where the day stays in range). Validated 6/24: calmest-20% HELD 96%.
  - PUT-covered     = trend cohort: atm_iv in the high band (HELD low ~40%). PROXY for the
                      OA put gate VIX>=22 (level, not change).
  - CALL track      = VIX Change% < -2 -> NOT MEASURABLE here (no VIX-change column). Reported
                      as a caveat, never silently folded in.
  - UNCOVERED       = the middle band claimed by neither -> the empty cell we quantify
                      (days/year + character: exc, |gap|, day-of-week).

Judge coverage by HELD-rate per band, not P&L (premium-contaminated — the C1 v1 lesson).
Bars are tunable (--ic-bar / --trend-bar) — the calm/trend cutoffs are a judgment call; the
band table shows the full HELD curve so the cut can be set from the data.

OUTPUT: data/regime_coverage.md (generated; do not hand-edit) + a console summary.
NOT wired into daily.sh — this is a one-time census, refreshed only when C1 re-runs.

Usage:
  python3 scripts/regime_coverage.py                     # reads data/c1_rows.csv
  python3 scripts/regime_coverage.py path/to/c1_rows.csv
  python3 scripts/regime_coverage.py --demo              # self-test on synthetic separable data
"""
import sys, os, csv, statistics as st, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IC_BAR = 0.90       # HELD-rate at/above this in a low-IV band => IC has edge (covered)
TREND_BAR = 0.55    # HELD-rate at/below this => trend cohort (put-directional covered)
N_BANDS = 10        # atm_iv deciles
TRADING_DAYS_YR = 252.0


def _f(x):
    try: return float(x)
    except (TypeError, ValueError): return None


def load(path):
    rows = []
    with open(path) as fh:
        for r in csv.DictReader(fh):
            iv = _f(r.get("atm_iv"))
            held = _f(r.get("held"))
            if iv is None or held is None:
                continue
            rows.append({
                "date": (r.get("date") or "").strip(),
                "atm_iv": iv, "atr5": _f(r.get("atr5")), "gap_pct": _f(r.get("gap_pct")),
                "exc": _f(r.get("exc")), "held": int(held),
                "stayed075": int(_f(r.get("stayed075")) or 0),
            })
    return rows


def _dow(dstr):
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%Y%m%d"):
        try: return datetime.datetime.strptime(dstr[:10], fmt).strftime("%a")
        except ValueError: continue
    return "?"


def bands(rows, k):
    """Split into k atm_iv-quantile bands (low IV -> high IV)."""
    srt = sorted(rows, key=lambda r: r["atm_iv"])
    n = len(srt); out = []
    for i in range(k):
        lo = i * n // k; hi = (i + 1) * n // k
        chunk = srt[lo:hi]
        if chunk:
            out.append(chunk)
    return out


def cov_class(held_rate, mean_iv, iv_median):
    if held_rate >= IC_BAR and mean_iv <= iv_median:
        return "IC (calm)"
    if held_rate <= TREND_BAR and mean_iv >= iv_median:
        return "PUT (trend)"
    return "UNCOVERED"


def build(rows):
    n = len(rows)
    yrs = n / TRADING_DAYS_YR
    base_held = sum(r["held"] for r in rows) / n
    base_stay = sum(r["stayed075"] for r in rows) / n
    iv_med = st.median(r["atm_iv"] for r in rows)

    L = ["# Regime-coverage map  ·  generated " + datetime.date.today().isoformat(),
         "",
         "> Generated by `scripts/regime_coverage.py` from `data/c1_rows.csv` "
         f"({n} labeled days ≈ {yrs:.1f} yrs). Do not hand-edit. Coverage judged by "
         "**HELD-rate** (did the short strikes survive), not P&L. `atm_iv` is a relative "
         "regime signal (noisy level → read bands/percentiles, not absolute IV).",
         "",
         f"**Base rates:** HELD {base_held:.0%}  ·  STAYED075 {base_stay:.0%}  ·  "
         f"atm_iv median {iv_med:.3f}",
         "",
         "> ⚠️ **Call track (VIX Change% < −2) is NOT in this census** — c1_rows has no "
         "VIX-change column (QC VIX feed crashed; atm_iv is the proxy). Only the IC (calm) "
         "and put (trend) tracks are measurable here. The call track's low-vol relief-rally "
         "cohort partially overlaps the calm band but can't be cleanly separated without "
         "VIX-change data.",
         "",
         "## ATM-IV band census (low IV → high IV)",
         "| Band | n | days/yr | mean IV | HELD | STAYED075 | mean exc | mean \\|gap\\| | coverage |",
         "|--:|--:|--:|--:|--:|--:|--:|--:|:--|"]

    tallies = {"IC (calm)": [], "PUT (trend)": [], "UNCOVERED": []}
    for i, b in enumerate(bands(rows, N_BANDS), 1):
        m = len(b)
        hr = sum(r["held"] for r in b) / m
        sr = sum(r["stayed075"] for r in b) / m
        miv = st.mean(r["atm_iv"] for r in b)
        exc = st.mean(r["exc"] for r in b if r["exc"] is not None) if any(r["exc"] is not None for r in b) else float("nan")
        gaps = [abs(r["gap_pct"]) for r in b if r["gap_pct"] is not None]
        gp = st.mean(gaps) if gaps else float("nan")
        cls = cov_class(hr, miv, iv_med)
        tallies[cls].extend(b)
        L.append(f"| {i} | {m} | {m/yrs:.0f} | {miv:.3f} | {hr:.0%} | {sr:.0%} | "
                 f"{exc:.2f}% | {gp:.2f}% | {cls} |")

    # coverage summary
    L += ["", "## Coverage summary"]
    for cls in ("IC (calm)", "PUT (trend)", "UNCOVERED"):
        g = tallies[cls]
        if not g:
            L.append(f"- **{cls}:** 0 days"); continue
        L.append(f"- **{cls}:** {len(g)} days ({len(g)/n:.0%}, ~{len(g)/yrs:.0f}/yr) · "
                 f"HELD {sum(r['held'] for r in g)/len(g):.0%}")

    unc = tallies["UNCOVERED"]
    if unc:
        L += ["", "## The empty cell — uncovered-day character",
              f"{len(unc)} days (~{len(unc)/yrs:.0f}/yr) fire neither the IC calm gate nor the "
              "put trend gate. These are where new research earns the most."]
        excs = [r["exc"] for r in unc if r["exc"] is not None]
        gaps = [abs(r["gap_pct"]) for r in unc if r["gap_pct"] is not None]
        hr = sum(r["held"] for r in unc) / len(unc)
        if excs: L.append(f"- Excursion: mean {st.mean(excs):.2f}%, median {st.median(excs):.2f}% "
                          f"(vs full-set base) — HELD {hr:.0%} = coin-flippier than the calm cohort.")
        if gaps: L.append(f"- |Gap|: mean {st.mean(gaps):.2f}%.")
        dows = {}
        for r in unc:
            d = _dow(r["date"]); dows[d] = dows.get(d, 0) + 1
        if dows and "?" not in dows:
            L.append("- Day-of-week: " + " · ".join(f"{k} {v}" for k, v in
                     sorted(dows.items(), key=lambda kv: -kv[1])))
    L += ["", f"> Cut bars: IC-covered = HELD ≥ {IC_BAR:.0%} & IV ≤ median; "
          f"PUT-covered = HELD ≤ {TREND_BAR:.0%} & IV ≥ median (tunable via IC_BAR/TREND_BAR). "
          "The band table shows the full HELD curve so the cut can be set from the data."]
    return "\n".join(L) + "\n"


def _demo():
    """Synthetic separable data: low IV -> high HELD, high IV -> low HELD."""
    import random
    random.seed(7)
    rows = []
    for i in range(900):
        iv = random.uniform(0.1, 0.8)
        p_held = max(0.05, min(0.98, 1.3 - 1.6 * iv))   # calm -> holds, trend -> touched
        held = 1 if random.random() < p_held else 0
        exc = abs(random.gauss(0, 0.4 + iv))
        rows.append({"date": f"2023-{1+i%12:02d}-{1+i%28:02d}", "atm_iv": iv,
                     "atr5": iv*0.9, "gap_pct": random.gauss(0, 0.3), "exc": exc,
                     "held": held, "stayed075": 1 if exc <= 0.75 else 0})
    return rows


def main():
    args = [a for a in sys.argv[1:]]
    if "--demo" in args:
        rows = _demo()
        print(build(rows))
        print("\n[demo] self-test OK — logic runs on synthetic separable data.")
        return
    path = next((a for a in args if not a.startswith("-")), os.path.join(ROOT, "data", "c1_rows.csv"))
    if not os.path.exists(path):
        sys.exit(f"[blocked] {path} not found. Export c1_rows.csv from the QC ObjectStore "
                 f"(algorithm lean/c1_regime.py) and drop it in data/. Then re-run.")
    rows = load(path)
    if not rows:
        sys.exit(f"[error] no usable rows parsed from {path} (need atm_iv + held columns).")
    md = build(rows)
    out = os.path.join(ROOT, "data", "regime_coverage.md")
    open(out, "w").write(md)
    print(md)
    print(f"\n[wrote] {out}  ·  {len(rows)} days")


if __name__ == "__main__":
    main()
